# Generated by Django 2.1 on 2018-08-02 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('thug', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='log',
            name='image',
        ),
        migrations.AddField(
            model_name='log',
            name='image_url',
            field=models.CharField(blank=True, max_length=2000),
        ),
    ]
